[package]
name = "json-serde"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_core = { workspace = true }

[dev-dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
