[package]
name = "typify-macro"
version = "0.0.6-dev"
authors = ["Adam H. Leventhal <ahl@oxidecomputer.com"]
edition = "2018"
license = "Apache-2.0"
description = "typify macro implementation"
repository = "https://github.com/oxidecomputer/typify"
readme = "../README.md"

[dependencies]
quote = "1.0"
schemars = "0.8"
serde_json = "1.0"
syn = "1.0"
typify-impl = { version = "0.0.6-dev", path = "../typify-impl" }
proc-macro2 = "1.0"

[lib]
proc-macro = true
