[package]
name = "typify-macro"
version = "0.0.11-dev"
authors = ["Adam H. Leventhal <ahl@oxidecomputer.com"]
edition = "2021"
license = "Apache-2.0"
description = "typify macro implementation"
repository = "https://github.com/oxidecomputer/typify"
readme = "../README.md"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
schemars = "0.8.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_tokenstream = "0.1.7"
syn = "1.0"
typify-impl = { version = "0.0.11-dev", path = "../typify-impl" }