[package]
name = "typify-macro"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "typify macro implementation"
repository = "https://github.com/oxidecomputer/typify"
readme = "../README.md"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.36"
schemars = "0.8.21"
semver = { version = "1.0.23", features = ["serde"] }
serde = "1.0.203"
serde_json = "1.0.117"
serde_tokenstream = "0.2.1"
syn = { version = "2.0", features = ["full", "extra-traits"] }
typify-impl = { version = "0.1.0", path = "../typify-impl" }
