[package]
name = "typify-test"
version = "0.0.0"
edition = "2021"

[dependencies]
regress = "0.10.0"
serde = "1.0.206"
serde_json = "1.0.122"

[build-dependencies]
ipnetwork = { version = "0.20.0", features = ["schemars"] }
prettyplease = "0.2.20"
schemars = "0.8.21"
serde = "1.0.206"
syn = "2.0.74"
typify = { path = "../typify" }
