[package]
name = "typify-test"
version = "0.0.0"
authors = ["Adam H. Leventhal <ahl@oxidecomputer.com>"]
edition = "2021"

[dependencies]
regress = "0.5.0"
serde = "1.0.155"
serde_json = "1.0.94"

[build-dependencies]
ipnetwork = { version = "0.20.0", features = ["schemars"] }
schemars = "0.8.12"
serde = "1.0.155"
typify = { path = "../typify" }
