[package]
name = "typify-test"
version = "0.0.0"
edition = "2021"

[dependencies]
regress = "0.8.0"
serde = "1.0.196"
serde_json = "1.0.113"

[build-dependencies]
ipnetwork = { version = "0.20.0", features = ["schemars"] }
prettyplease = "0.2.16"
schemars = "0.8.16"
serde = "1.0.196"
syn = "2.0.49"
typify = { path = "../typify" }
