[package]
name = "typify-test"
version = "0.0.0"
edition = "2021"

[dependencies]
regress = "0.7.1"
serde = "1.0.189"
serde_json = "1.0.107"

[build-dependencies]
ipnetwork = { version = "0.20.0", features = ["schemars"] }
prettyplease = "0.2"
schemars = "0.8.15"
serde = "1.0.189"
syn = "2.0.38"
typify = { path = "../typify" }
