[package]
name = "typify-test"
version = "0.0.0"
edition = "2021"

[dependencies]
regress = "0.7.1"
serde = "1.0.187"
serde_json = "1.0.104"

[build-dependencies]
ipnetwork = { version = "0.20.0", features = ["schemars"] }
prettyplease = "0.2"
schemars = "0.8.12"
serde = "1.0.187"
syn = "2.0.28"
typify = { path = "../typify" }
