[package]
name = "typify-test"
version = "0.0.6-dev"
authors = ["Adam H. Leventhal <ahl@oxidecomputer.com>"]
edition = "2018"

[dependencies]
schemars = "0.8"
serde = "1.0"

[build-dependencies]
schemars = "0.8"
serde_json = "1.0"
typify = { path = "../typify" }
