[package]
name = "typify-test"
version = "0.0.0"
edition = "2021"

[dependencies]
regress = "0.10.1"
serde = "1.0.215"
serde_json = "1.0.133"

[build-dependencies]
ipnetwork = { version = "0.20.0", features = ["schemars"] }
prettyplease = "0.2.25"
schemars = "0.8.21"
serde = "1.0.215"
syn = "2.0.90"
typify = { path = "../typify"}
